version: '3'
services:
  app:
    image: node:latest # Gunakan versi Node.js yang diinginkan
    container_name: frontend
    working_dir: /client
    volumes:
      - ./client:/client
    ports:
      - "3000:3000"
    command: npm start

  database:
   image: postgres:13
   container_name: database
   hostname: database
   restart: always
   environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=qwerty123
    - POSTGRES_DB=pacmail
   ports:
    - "5432:5432"
   volumes:
    - postgres_data:/var/lib/postgresql/data