version: '3'
services:
  frontend:
    image: node:latest
    container_name: frontend
    working_dir: /frontend
    restart: always
    depends_on:
      - database
      - backend
    volumes:
      - ./frontend:/frontend
    command: npm start
    network_mode: host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    hostname: backend
    restart: always
    depends_on:
      - database
    volumes:
      - ./backend:/backend
    network_mode: host

  database:
    image: postgres:13
    container_name: database
    hostname: database
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host


volumes:
  postgres_data:
  minio_data:

networks:
  pacmail: