version: '3'
services:
  app:
    image: node:latest # Gunakan versi Node.js yang diinginkan
    container_name: frontend
    working_dir: /client
    volumes:
      - ./client:/client
    ports:
      - "3000:3000"
    command: npm start