version: '3'
services:
  frontend:
    image: node:latest # Gunakan versi Node.js yang diinginkan
    container_name: frontend
    working_dir: /frontend
    restart: always
    depends_on:
      - database
      - backend
    volumes:
      - ./frontend:/frontend
    command: npm start
    network_mode: host

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    hostname: backend
    restart: always
    depends_on:
      - database
    volumes:
      - ./backend:/backend
    network_mode: host

  database:
    image: postgres:13
    container_name: database
    hostname: database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=pacmail
    volumes:
      - postgres_data:/var/lib/postgresql/data
    network_mode: host
    
volumes:
  postgres_data:

networks:
  pacmail: